baseurl = "https://blog.kazu634.com/"
title = "His greatness lies in his sense of responsibility"
DefaultContentLanguage = "ja"
languageCode = "ja"
theme = "angels-ladder"
HasCJKLanguage = true

[params]
  subtitle = "named after the quotation from Wind, Sand, and Stars by Saint Exupery."
  facebook = "https://www.facebook.com/kazu634"
  twitter = "https://twitter.com/MusashiKazuhiro"
  github = "https://github.com/kazu634"
  profile = "/images/profile.png"
  analytics = "UA-57665492-1"
  copyright = "Written by Kazuhiro MUSASHI"

  description = "the blog written by @MusashiKazuhiro"
  title = "His greatness lies in his sense of responsibility"
  images = ["/images/profile.png"]

[taxonomies]
  series = "series"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "monokai"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe= true
