version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest

    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s /root/project/
      - run:
          name: "Test Website"
          command: htmlproofer /root/project/public --allow-hash-href --check-html --empty-alt-ignore --disable-external

